<?php

namespace AppBundle\Repository;

/**
 * Playlist_musicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Playlist_musicRepository extends \Doctrine\ORM\EntityRepository
{
}
