<?php

namespace AppBundle\Repository;

/**
 * Room_waiting_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Room_waiting_listRepository extends \Doctrine\ORM\EntityRepository
{
  public function findOneByUserAndRoom($user, $room)
  {
    $qb = $this->createQueryBuilder('rwl');

    $qb->where('rwl.user = :user')
          ->setParameter('user', $user)
       ->andWhere('rwl.room = :room')
          ->setParameter('room', $room);

    return $qb->getQuery()->getOneOrNullResult();
  }

  public function getFirstDj($room)
  {
    $qb = $this->createQueryBuilder('rwl');

    $qb->where('rwl.room = :room')
          ->setParameter('room', $room)
        ->orderBy('rwl.id', 'ASC')
        ->setMaxResults(1);

    return $qb->getQuery()->getOneOrNullResult();
  }

  public function getNbDj($room)
  {
    $qb = $this->createQueryBuilder('rwl');

    $qb->where('rwl.room = :room')
          ->setParameter('room', $room);

    return count($qb->getQuery()->getResult());
  }
}
