<?php

namespace AppBundle\Repository;

/**
 * Room_actual_musicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Room_actual_musicRepository extends \Doctrine\ORM\EntityRepository
{
}
