<?php

namespace AppBundle\Repository;

/**
 * UserRoomFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoomFollowRepository extends \Doctrine\ORM\EntityRepository
{
  public function findOneByUserAndRoom($user, $room)
  {
    $qb = $this->createQueryBuilder('urf');

    $qb->where('urf.user = :user')
          ->setParameter('user', $user)
       ->andWhere('urf.room = :room')
          ->setParameter('room', $room);

    return $qb->getQuery()->getResult();
  }
}
