<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Room extends \AppBundle\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'nbFollowers', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'music_types', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'waiting_list', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'actual_music'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'nbFollowers', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'music_types', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'waiting_list', '' . "\0" . 'AppBundle\\Entity\\Room' . "\0" . 'actual_music'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Room $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbFollowers($nbFollowers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbFollowers', [$nbFollowers]);

        return parent::setNbFollowers($nbFollowers);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbFollowers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbFollowers', []);

        return parent::getNbFollowers();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addMusicType(\AppBundle\Entity\Room_music_type $musicType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMusicType', [$musicType]);

        return parent::addMusicType($musicType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMusicType(\AppBundle\Entity\Room_music_type $musicType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMusicType', [$musicType]);

        return parent::removeMusicType($musicType);
    }

    /**
     * {@inheritDoc}
     */
    public function getMusicTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMusicTypes', []);

        return parent::getMusicTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addWaitingList(\AppBundle\Entity\Room_waiting_list $waitingList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWaitingList', [$waitingList]);

        return parent::addWaitingList($waitingList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWaitingList(\AppBundle\Entity\Room_waiting_list $waitingList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWaitingList', [$waitingList]);

        return parent::removeWaitingList($waitingList);
    }

    /**
     * {@inheritDoc}
     */
    public function getWaitingList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWaitingList', []);

        return parent::getWaitingList();
    }

    /**
     * {@inheritDoc}
     */
    public function setActualMusic(\AppBundle\Entity\Room_actual_music $actualMusic = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActualMusic', [$actualMusic]);

        return parent::setActualMusic($actualMusic);
    }

    /**
     * {@inheritDoc}
     */
    public function getActualMusic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualMusic', []);

        return parent::getActualMusic();
    }

}
